### ISSUE TITLE
Add option for appending timestamps to RPM snapshots

### ISSUE THREAD

**Issue by keirlawson** [sbt/sbt-native-packager#1008]
To differentiate between multiple different snapshot RPMs it would be great to have a (off by default) flag the would automatically append the timestamp to the RPM version, similar to what the Maven RPM plugin does by default: http://www.mojohaus.org/rpm-maven-plugin/version-mojo.html#release

**Comment by muuki88** [comment]
Thanks for your feature request.

IMHO this is something we shouldn't add a setting for. We either implement it by default or we provide a simple recipe on how to implement it yourself as this is straightforward to do. [sbt-release](https://github.com/sbt/sbt-release) has some examples on how to set release versions.

**Comment by keirlawson** [comment]
Ok that sounds reasonable, I guess the argument in favour of doing it by default is it mirrors what the Maven plugin does making it an easier switch, argument against is that its possibly surprising/non-obvious.  Certainly as someone coming from Maven having it there by default would help my use case however I don't know how representative my own use case is.

**Comment by muuki88** [comment]
Cool. Thanks for your understanding 😊 
Releasing is not strictly a part of native-packager so I'm always very suspicious if it should be included.

**Comment by dpennell** [comment]
@keirlawson the `rpmRelease` setting provides a convenient way to do what you want.  See https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch01s03.html for background.  We've been using a timestamp formatted in sorting order (YYYY.MM.DD.HH.MM.SS.UTC) to achieve maven snapshot-like behavior with yum install/upgrade.  We are in the process of moving to using sbt-dynver instead of simple timestamps.
