### ISSUE TITLE
APP_CLASSPATH line growths too long in windows startup batch script

### ISSUE THREAD

**Issue by torao** [sbt/sbt-native-packager#1071]
## Expected behaviour

Batch script that made by `universal:packageBin` for Windows 10 starts my application.

## Actual behaviour

"Input line is too long” error is shown.

## Information

The problem is that the line `set APP_CLASSPATH=...` in batch file exceeds the Windows limit of 8,191 chars when dependency libraries in project increases.  

It's able to avoid this limitation to divide into multiple lines instead of setting classpath on one line.

```
set "APP_CLASSPATH=%APP_LIB_DIR%\library1.jar"
set "APP_CLASSPATH=%APP_CLASSPATH%;%APP_LIB_DIR%\library2.jar"
set "APP_CLASSPATH=%APP_CLASSPATH%;%APP_LIB_DIR%\library3.jar"
...
```

I think it seems to be enough to fix 
```scala
"set \"APP_CLASSPATH=" + (cp map { path =>
  if (isAbsolute(path)) path else makeRelativePath(path)
} mkString ";") + "\""
```
in file  [BatStartScriptPlugin.scala](https://github.com/sbt/sbt-native-packager/blob/cee8a0750ed56c3409f9ea59a143b0691d655ef3/src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BatStartScriptPlugin.scala#L144) to like follows
```scala
val files = cp map { path => if (isAbsolute(path)) path else makeRelativePath(path) }
"set \"APP_CLASSPATH=" + files.head + "\"" + System.lineSeparator() + (files.drop(1) map { path =>
  "set \"APP_CLASSPATH=%APP_CLASSPATH%" + File.pathSeparator + path + "\""
} mkString System.lineSeparator())
```
.

- Terminal on IntelliJ IDEA 2017.2.6
- sbt 1.0.4
- sbt-native-packager 1.3.1 and 1.1.4
- Java 1.8.0_141
- Scala 2.12.4
- build and target system is Windows 10

![2017-11-29 16 35 30](https://user-images.githubusercontent.com/836654/33364895-b24d62ce-d529-11e7-846d-69b55b800cfe.jpg)

**Comment by dwickern** [comment]
This is a common problem on Windows. Splitting up the `set APP_CLASSPATH=...` onto multiple lines won't help: running the concatenated command string will fail due to the same 8192 character limit.

I'd recommend generating a classpath jar. Have a look at [Dealing with long classpaths](http://sbt-native-packager.readthedocs.io/en/stable/recipes/longclasspath.html#long-classpaths)

**Comment by torao** [comment]
argh. that's right. Thank you for your information, I solved my problem to use classpath jar. Thanks!

**Comment by atrosinenko** [comment]
I have faced with the same problem. For me, it helper to manually replace the classpath string in the .bat file with

    set "APP_CLASSPATH=%APP_LIB_DIR%\*"

AFAIK this can introduce subtle errors because of unstable classpath ordering, but is this a problem for well-formed jars that do not share the same fully qualified class names? If so, would addition of an sbt option to generate wildcard classpath solve this issue? Of course, a warning should be written for this option in the docs and maybe even to console.
