### ISSUE TITLE
windows installer

### ISSUE THREAD

**Issue by imeredith** [sbt/sbt-native-packager#12]
Just fyi Jenkins uses https://github.com/kohsuke/winsw for installing itself, and its slaves as windows a windows service.

Not sure what else there is out there.

**Comment by 16bytes** [comment]
For what it's worth, you might consider using [procrun](http://commons.apache.org/proper/commons-daemon/procrun.html) from the commons-daemon project as an alternative to winsw.  This is what tomcat uses.  In fact, I'm not sure why Jenkins didn't use procrun since it's almost the same thing with a similar permissive license (apache).

Advantages include having the binary up on [the maven repo](http://search.maven.org/#artifactdetails|commons-daemon|commons-daemon|1.0.15|jar), though it's not listed in a configuration in the pom anywhere so you have to manually pull it.

Another advantage would be that it's java specific so you can, for example, supply a stop() method that is called when the service is stopped.

**Comment by muuki88** [comment]
Thanks for the suggestion! At the first look procrun looks pretty solid regarding features and maturity.

Do you have any time to start a initial pull request? If you need any help setting things up or a general idea how to implement, I'm more than happy to help.

**Comment by schmitch** [comment]
It would be great if somebody is willed to address this issue. Maybe I could ask my employer to raise some bucks for it.

**Comment by muuki88** [comment]
There is still an open pull request. Maybe you could start there.

**Comment by schmitch** [comment]
actually I have zero experience with the codebase I doubt that I can't pull that off :(

**Comment by muuki88** [comment]
If you take a look at #329 the changes are rather simple

- Add a way to download the windows-service executable
- Add necessary configuration to the `WixHelper`
- Add executable and configuration to `mappings in Windows`

The code alright is in a acceptable shape. It only needs some testing, maybe configuration tweaks and documentation.

**Comment by schmitch** [comment]
easier as said
