### ISSUE TITLE
AshScriptPlugin - Missing addResidual method in script

### ISSUE THREAD

**Issue by rfranco** [sbt/sbt-native-packager#1264]
## Expected behaviour

```
sbt docker:publishLocal
docker run $IMAGE abc
```

## Actual behaviour

```
/opt/docker/bin/script: line 79: addResidual: not found
```

## Problem

It's missing the addResidual method in [script](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template#L79)

## Information

- What sbt-native-packager are you using
1.4.1
- What sbt version
1.3.2
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
MacOs
- What package are you building (e.g. docker, rpm, ...)
docker
- What version has your build tool (find out with e.g. `rpm --version`)
Docker version 19.03.2, build 6a30dfc
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)
Alpine

**Comment by muuki88** [comment]
Thanks @rfranco for your bug report. This looks very much like a bug. Do you have the time to fix this? I would be very happy to merge a PR for this :heart_eyes: Feel free to ask for help :smiley:

**Comment by archeuclid** [comment]
Hello
I wrote some minimal code to fix the issue. Added a new plugin and associated keys with sh template. Tested on Ubuntu 18 with Scala 2.13.1. App starts with the script as well as in openjdk:8-jre-alpine Docker image.

**Comment by muuki88** [comment]
Thanks a lot @archeuclid :heart_eyes: 

> I wrote some minimal code to fix the issue. 

This already looks like a full fledged solution :sunglasses: I was wondering why you duplicate the settings for `ash`. In the end the user needs a single type of start script. The current [AshScriptPlugin](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/AshScriptPlugin.scala) overrides / extends the `bash` script settings. I agree that the naming is not ideal. `shell` would probably be better. 

Still duplicating adds a few issues.

- we need to disable the `BashScriptPlugin` otherwise we have race conditions as the same script is generated by bash and ash
- if we generate different scripts, we need to change entrypoints (e.g. the [`dockerEntrypoint`](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L107))

> Still need to add forwarder template, cygwin portability, and tests.

I wouldn't care if the `cygwin` portability is missing in the beginning. How runs cygwin in docker :joy: ? We can add this if someone really needs this.

> I suggest to define some minimal specifications to all the scripts that are produced (e.g inherit or determine java launching tools, template replacements guide, main class and classpath determination). That is, outline all the specs. That way all the scripts will be in order and can be tested. Also, it is best to adopt a style guide for sh or bash scripts.

I really like this idea. I have to admit by bash knowledge is limited to the things I require (which is not much). We have very confusing summary of settings hidden [in the archetype cheatsheet](https://sbt-native-packager.readthedocs.io/en/latest/archetypes/cheatsheet.html#bash-script-src-templates-bash-template) and [Java Command Line Application / Start script options section](https://sbt-native-packager.readthedocs.io/en/latest/archetypes/java_app/index.html#start-script-options) and [Start script customizations](https://sbt-native-packager.readthedocs.io/en/latest/archetypes/java_app/customize.html#start-script-customizations).

This would be a brilliant thing to merge this into a single documentation page. Or at least to have a single page that points to these different locations.

**Comment by archeuclid** [comment]
I suggest that the start script should:

1. Resolve java (from environment or whatever method, and all the version checking if necessary).
2. Provide a default template and a list of replacements allowed in it (should be strictly outlined and checked somehow - someone in the future will inject something that will break things).
3. Resolve main class.
4. Resolve classpath.
5. Resolve jvm options and jvm arguments (either environment or directly passed to the script).
* There should be ordering priority - script args first, environment second, e.g.

No more, no less. That is no adding additional bundled jvm's, reading configs from other scripts etc. It is too much. Easier if all the responsibilities are outlined and are minimal. If there is a need for additional feature - create a new starter trait with all the things.

Just saying, lol. In the end, it is better to use python. 

I refactored some more today. Will not PR until all the things are tested though.

**Comment by theon** [comment]
Hi, I was also receiving getting the `line 79: addResidual: not found` error, but upgrading to the `1.8.0` seems to have resolved the issue for me 👍
