### ISSUE TITLE
Prevent pushing no-repository images to dockerhub?

### ISSUE THREAD

**Issue by CB-andrewehrlich** [sbt/sbt-native-packager#1265]
I am tagging my images with ```myrepo/image:tag``` as well as just ```image:tag```. I need the ```image:tag``` format for running locally in dev env. But, ```sbt docker:publish``` tries to push the ```image:tag``` images up to dockerhub, when I would rather that it didn't try to publish them anywhere. Is there any way to get that behavior?

**Comment by muuki88** [comment]
Hi @CB-andrewehrlich 

Thanks for your question. You need to use the `docker:publishLocal` task to push to your local registry :smiley:

**Comment by CB-andrewehrlich** [comment]
The problem is that I need to use docker:publish to push to my private repo. But when I run that task, the no-tag image (image:tag) attempts to go to dockerhub, when it ought to do nothing.

**Comment by nigredo-tori** [comment]
I'm using Docker terminology (registry, tag) instead of `DockerPlugin` one (repository, alias) here for clarity.

@CB-andrewehrlich, Docker tags are the coordinates for where your images will be pushed. So if you have `foo:123/bar/baz:qux` as your `Docker/dockerAlias` (`foo:123` is your registry), then `Docker/publishLocal` will build a *local* image ` `foo:123/bar/baz:qux`. `Docker/publish` just pushes the built images to their respective registries. If in the tag doesn't specify the registry, it is assumed (by the Docker itself) to be the default global Docker registry. That is, `bar/baz:qux` is assumed to be a local version (pulled, or pending push) of `docker.io/bar/baz:qux`.

So when you say that you want `publishLocal` to build `baz:qux`, but `publish` to not push it, you stray from the general Docker conventions. I fail to see why this is necessary, and why the `DockerPlugin` should support this functionality by default. If you have `publish`ed a `foo:123/bar/baz:qux`, then it should already be accessible locally under the same tag - why do you need to add another tag, with some non-obvious behavior?

**Comment by CB-andrewehrlich** [comment]
Yea, that's eventually the conclusion I came to, that Docker assumes no-repo is a synonym for Dockerhub, and there is no real way around that.
