### ISSUE TITLE
Version check not working for openjdk 11

### ISSUE THREAD

**Issue by yogeshbidari** [sbt/sbt-native-packager#1331]
I am facing similar issue as https://github.com/sbt/sbt-native-packager/issues/1145
Updated plugin sbt-native-packager version to 1.3.6, still the issue exist.

## Actual behaviour
App LOG:

The java installation you have is not up to date
requires at least version 1.6+, you have
version 11.0.6

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .

## Information

- What sbt-native-packager are you using 1.3.6
- What sbt version 0.13.11
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) 
- What package are you building (e.g. docker, rpm, ...)
- What version has your build tool (find out with e.g. `rpm --version`)
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)

**Comment by dr0i** [comment]
For anyone who crosses this issue:
You can do `sbt stage` which creates the start script at `./target/universal/stage/bin/`. You can execute this script and provide parameters like ` -Dhttp.port=$PORT -no-version-check`. The ` -no-version-check` supresses the checking of the java version  (which is buggy in sbt because 11 > 1.6 ).
