### ISSUE TITLE
`sbt stage` fails when `sbt compile` succeeds

### ISSUE THREAD

**Issue by arjundhawan-tomtom** [sbt/sbt-native-packager#1364]
## Expected behaviour

`sbt stage` should successfully compile a project (involving macros), whenever `sbt compile` successfully compiles a project.

## Actual behaviour

`sbt stage` fails on compilation, whereas `sbt compile` succeeds. The problem seems to lie with macros, in particular the `zio.macros.accessible` annotation (https://zio.dev/docs/howto/howto_macros#description).

I have annotated an object like so:
```
@accessible
object Foo {
```
Which is generating the function in the object `Foo`: `Foo.functionA`.
When running `sbt stage`, compilation fails however with error:
```
[error] /***/Main.scala:54:30: value functionA is not a member of object foo.Foo
[error]   val program = Foo.functionA
```
Note that `sbt compile`, or `sbt assembly` (using the `sbt-assembly` plugin) work fine.

## Information

- What sbt-native-packager are you using: 1.7.4, 1.7.5
- What sbt version: 1.3.10, 1.3.13
- scala version: 2.13.3
- What is your build system: Ubuntu 18.04.5 LTS
- What package are you building: `JavaServerAppPackaging`

**Comment by muuki88** [comment]
Hi @arjundhawan-tomtom 

Thanks for the detailed description.

This sounds very odd to me. My first intuition this is an issue with the scala docs generation, because

- it is triggered during stage IIRC
- it is not triggered during `compile` or `assembly`
- it is a separate scalac instance with different settings

Can you try turning off docs generation? I think this may work

```sbt
Compile / doc / sources := Seq.empty
```

Source: https://www.playframework.com/documentation/2.8.x/sbtCookbook

**Comment by arjundhawan-tomtom** [comment]
@muuki88 wow, great intuition! Indeed it scaladoc is the culprit here. The issue seems to be a 7 years (!) old bug: https://stackoverflow.com/questions/42684101/scaladoc-generation-fails-when-referencing-methods-generated-by-annotation-macro 
Sorry for the inconvenience, issue closed.

**Comment by muuki88** [comment]
> This is a bug in Scala, still present in 2.13.

Oh boy :joy: This will never end

> Sorry for the inconvenience, issue closed.

No worries :kissing_heart:
