### ISSUE TITLE
Support Mac OS X app bundle

### ISSUE THREAD

**Issue by choffmeister** [sbt/sbt-native-packager#253]
Are there any efforts to support app bundles for Mac OS X like https://github.com/sbt/sbt-appbundle does? Sadly the sbt-appbundle package lacks maintainence...

**Comment by metasim** [comment]
@choffmeister , @muuki88 With the `JDKPackager` plugin, this is (arguably) covered. What do we need to do to close this issue?

**Comment by muuki88** [comment]
@metasim you're right. I think there is a dmg-doc section. We should reference the jdkPackager there.

**Comment by akauppi** [comment]
Seconding this. Can help to test.

**Comment by muuki88** [comment]
@akauppi That would be awesome. The current version `1.0.2` should have everything you need to do so. The default `jdkPackagerType` is `installer`, so on MacOS X this _should_ generate dmg and app files. However you can set various types in your `build.sbt`

```scala
enablePlugins(JDKPackagerPlugin)

// simple dmg
jdkPackagerType := "dmg"

// macos app
jdkPackagerType := "mac.appStore"
```

and then run

```
sbt jdkPackager:packageBin
```

@metasim correct me if anything should be incorrect.

**Comment by mariussoutier** [comment]
Will this include an entire JRE?

**Comment by muuki88** [comment]
AFAIK this is configurable

**Comment by metasim** [comment]
@muuki88 As far as I know, that should work, except I've never tried the `mac.appStore` type myself.
These are the currently valid options: `all, deb, dmg, exe, image, installer, mac.appStore, msi, none, pkg, rpm`. Wondering if I should have made a set of case objects instead of using a string here.

On MacOS, if you select `installer`, it creates both `.dmg` and `.pkg` packages (the latter being more like the traditional windows installer).

@mariussoutier I does indeed include the JRE. I'm not sure if you *can* configure it to deploy without it. You'd have to check the JavaFX Ant Task documentation. Know that a `build.xml` file is generated in then `target/jdkpackager` directory, which you can inspect/tweak to try things out via running Ant directly. If you find something you want but isn't currently supported in the plugin, then you can intercept the task that writes that file to apply additional XML transforms on it if you had to, then file a feature request or PR to add it to the plugin. One thing I haven't figured out how to do is have the installer include other resources (e.g. from the `mappings` setting) that aren't *inside* the `.app` bundle, but co-located in the `.dmg`. Not even sure if it's possible with the Oracle tools.

**Comment by mariussoutier** [comment]
Thanks for the info. Including the JRE is a sensible default to avoid the "You have to install Java" dialog.

**Comment by metasim** [comment]
I agree... huge simplification. But I actually think the reason they originally did it was because Apple wouldn't allow anything in the app store that required additional downloads :-/

**Comment by Christewart** [comment]
Is there any updates on this?

**Comment by muuki88** [comment]
Not really. If some one is willing to make a pull request implementing this, I'm happy to merge 😊
