### ISSUE TITLE
Custom configuration is replaced with the default one during package install

### ISSUE THREAD

**Issue by artempyanykh** [sbt/sbt-native-packager#378]
I'm not sure if what I'm doing is the right way of doing things. If there is a better way, please tell me.

However the problem is that when I install a deb. package with my Play 2 app, I get my custom production application.conf replaced with the default application.conf from sources. The whole story is as follows.

I have a Chef-repo with the description of my production configuration. As a part of provisioning process a custom application.conf with production settings (db, migrations, etc.) is placed at /etc/my_app/application.conf.

When the provisioning of production VM is completed, I continue with the my_app.deb package installation. I expect that after the package is installed, the application would be running with my production config. However during the installation production `/etc/my_app/application.conf` is replaced with default application.conf from the sources. Because of that application server can't start (and I actually get a flapping service with a stream of "can't connect to database[default]" in /var/upstart/my_app.log)
The same thing If I install a newer version of a package.

I really want to do the initial VM setup with Chef (including production application.conf generation), and want my production config to be persisted between package install/reinstall, but I don't understand where shall I put my config file and how I shall start a service, so the things would run smoothly.

**Comment by cbornet** [comment]
Hello @muuki88,

I think this is more a bug : the debian conffile in target/DEBIAN/conffile gets filled with a /usr/share/{app}/conf//application.log.
Because of the double-slash in the path, the file is not considered as a config file and thus it gets overriden.
The issue comes from Play! : https://github.com/playframework/playframework/blob/cc308ec87413081826d9a91d9cee10591880eaba/framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
<pre>
mappings in Universal ++= {
    val confDirectoryLen = confDirectory.value.getCanonicalPath.length
    val pathFinder = confDirectory.value ** ("*" -- "routes")
    pathFinder.get map {
        confFile: File =>
        confFile -> ("conf/" + confFile.getCanonicalPath.substring(confDirectoryLen))
    }
}
</pre>
confDirectory is "/conf" so confFile.getCanonicalPath.substring(confDirectoryLen) is "/application.conf"

My workaround is to post process the mappings in build.sbt
<pre>
mappings in Universal := {
    (mappings in Universal).value map {
        case (file,name) if name startsWith "conf//" => (file, "conf/" + name.substring(6))
        case (file,name) => (file,name)
    }
}
<pre>

But maybe there is a better solution ?

**Comment by muuki88** [comment]
That's definitely a bug! Adding `application.conf` as debian conffile seems reasonable, however the path should be correct.

**Comment by muuki88** [comment]
Did you open a bug for this on the playframework? 

cc @jroper

**Comment by jroper** [comment]
This is *probably* fixed in Play, here:

https://github.com/playframework/playframework/pull/4116
