### ISSUE TITLE
Warning when using 0.8.0 with Play 2.3.7

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-native-packager#459]
I doubt this is an sbt-native-packager bug, but I found the warning to be very strange and was wondering if you knew what was going on.

>[info] Loading project definition from /home/bmccann/src/connectifier/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.sbt:sbt-native-packager:0.7.4 -> 0.8.0
[warn] Run 'evicted' to see detailed eviction warnings

Should I be worried about using a new version than Play provides? Isn't this pretty typical for the dependency management to use the latest provided version of a library?

**Comment by muuki88** [comment]
This is a new feature of SBT. When overriding a plugin version you get a
warning what you override. Play ships with 0.7.4 and you override it with
0.8.0. Nothing magical going on :-)

**Comment by benmccann** [comment]
Thanks. Such a weird feature though. Do you know why they added it? It should be just fine for me to override Play's 0.7.4 and use 0.8.0 instead, right?

**Comment by muuki88** [comment]
Yep. If  you have special settings in your play project you may have to adjust them. Otherwise you can just upgrade.

Well, this feature is like the `libraryDependency` overrides. If you have multiple versions
of a single library that different other libraryDependencies depend on, that you get a
similar warning. The same with different scala versions.
