### ISSUE TITLE
Feedback on using JDKPackagerPlugin for some days (creating MSI)

### ISSUE THREAD

**Issue by akauppi** [sbt/sbt-native-packager#594]
The [plugin](http://www.scala-sbt.org/sbt-native-packager/formats/jdkpackager.html) really makes things easier. The documented features work, but I noticed some things I would want that are currently not supported.

1. Ability to launch the installed program right after installation. I do not know if this is possible via the `ant-javafx.jar`, either.
2. Ability to build in a specific, local JRE instead of the system default.
3. For some reason I am unable to sign the created MSI (separately, using `signtool`). Not asking signing to be included, but if the output MSI format is not allowing signing, that's a bug somewhere.
4. The icon in the `Remove Programs` list cannot be customized.

I'm just listing these as a feedback, and for others considering using the plugin. Unfortunately cannot help in adding such features. Sorry.

**Comment by metasim** [comment]
@akuppi Thanks so much for the feedback! 

As for Item 1, I think this is the default if you use InnoSetup instead of WiX. My memory is that if you select `all` or `installers` as the package type, the javapackager tasks will build all the ones it can, based on the tools available on the system. Also know that you can override the default InnoSetup or WiX configuration files. See [here](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#BCGICFDB) for details, but know I've not fully tested out this to ensure that the `build.xml` file the plugin generates properly configures the classpath.

Item 2: Not sure about this one. I thought I remembered seeing something in the past where one could configure this, but scouring [the docs](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/javafx_ant_task_reference.html) doesn't result in anything I can find.

Item 3: I'd take a look at the WiX documentation on that front. Please let us know if you find anything. Keep an eye on the [bundle arguments](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/javafx_ant_task_reference.html#CACDDFDF) documentation, as this is where the MacOS signing stuff is, and where I'd expect Oracle to add Windows support in subsequent releases.

Item 4: I think you'll have to go the route of drop-in resources (Item 1) to be able to do this, but not sure.

IHTH.

**Comment by metasim** [comment]
On Item 2, looking at the [Windows specific docs](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javapackager.html) for the *command line* `javapackager` tool (which uses the same code as the ant tasks IIRC), it references a bundle argument `runtime=path` that can be assigned via the command line via the `-B` option. So I'm wondering if you set a bundle argument (via the generated `build.xml`, file until I expose that to sbt) if that would do the trick?

**Comment by metasim** [comment]
@akauppi Per item 4, a colleague of mine figured out that if you use InnoSetup instead of WiX as the backend, the uninstaller icon is properly synced. I suspect this is a bug in `javapackager` WiX template.

Interested in knowing if you find a solution to item 3. I don't have experience signing Windows applications.

**Comment by akauppi** [comment]
Unfortunately, I remember very little of this, now two months later. We ended up doing the installer a completely different way.
