### ISSUE TITLE
docker plugin should require JavaAppPackaging

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt-native-packager#712]
https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L66

I need to add JavaAppPackaging manually or it fails with `opt` folder not found

**Comment by muuki88** [comment]
This is by design. `DockerPlugin` is just an _output format_ you can choose. `JavaAppPackaging` enables the `DockerPlugin`. If you only enable the `DockerPlugin` you are responsible for setting up your application yourself. Because that's a common problem, we have the `archetypes`, which do all the heavy lifting for you.

**Comment by MasseGuillaume** [comment]
Maybe we should document this http://www.scala-sbt.org/sbt-native-packager/formats/docker.html
