### ISSUE TITLE
Fix deprecation warnings in windows WixHelper

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#726]
Referring to https://github.com/scala/scala-dist/issues/158 the WixHelper has deprecation warnings since more than two years. We should either fix this or remove the deprecated annotation.

cc: @metasim @nazoking @bjuric

**Comment by metasim** [comment]
IMO, the WiX support overall could be considered deprecated in favor of JDKPackager (which allows you to use WiX if you want).

**Comment by metasim** [comment]
@muuki88 I added the deprecation description to remove another warning asking that deprecations have descriptions and dates. I think I guessed at the reason for the deprecation, and never asked @jsuereth. My suggestion, since the plugin is obviously working for some people, is to just remove the deprecation warning, converting it to an inline "TODO".

**Comment by SethTisue** [comment]
yes please

**Comment by muuki88** [comment]
@SethTisue happy to merge a pull request 😊

**Comment by SethTisue** [comment]
> happy to merge a pull request

a PR that does "remove the deprecation warning, converting it to an inline "TODO""? I can do that

**Comment by SethTisue** [comment]
PR: https://github.com/sbt/sbt-native-packager/pull/909

**Comment by muuki88** [comment]
Will release `1.1.5` and a `1.2.0 Milestone` today.
