### ISSUE TITLE
chown: invalid group `user:user`

### ISSUE THREAD

**Issue by martinstuder** [sbt/sbt-native-packager#776]
I'm using sbt-native-packager 1.1.0-RC3 with a Play Framework 2.3.8 application. Following some hints in https://github.com/sbt/sbt-native-packager/issues/554 and https://github.com/playframework/playframework/issues/4242 I got things as far as I can start and stop the application. When doing so, however, I encounter the following error:

```
[ZZZZZ /usr/share/app/conf]# service app start
chown: invalid group: `user:user'
Starting app:                                         [  OK  ]
```

Looking into the corresponding `/etc/init.d/app` script (on RHEL 6.4), I see
```
# create PIDDIR where PIDFILE will be kept
if [ -z "${PIDDIR:-}" ]; then
    PIDDIR=/var/run/app/
    mkdir -p $PIDDIR && chown $DAEMON_USER:$DAEMON_USER $PIDDIR
fi
```

Note the line `chown $DAEMON_USER:$DAEMON_USER`. Shouldn't it say `chown $DAEMON_USER:$DAEMON_GROUP`?

**Comment by muuki88** [comment]
Hi @martinstuder 

Thanks for you report. Indeed this looks like a bug. I assume `daemonUser` and `daemonGroup` have different settings in your `build.sbt`? ( a small sample to reproduce is always nice :) )

Would like to make a PR. The  [rpm-start-template](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template#L57) should be pretty simple to touch.

Another note: IIRC `play-2.3.8` is based on a pre-autoplugin (< 1.x.x.) version of native-packager, which creates some bizarre effects, when using both together. Since play 2.4.x the native-packager autoplugins are being used.
