### ISSUE TITLE
Mappings are not contained in JDKPackager bundles

### ISSUE THREAD

**Issue by smoes** [sbt/sbt-native-packager#782]
When creating bundles with JDKPackager (tried for .app, .dmg and .pkg on OSX), resources defined in mappings, defined as follows, are not included in the final bundle:

```
// Tried also 'in JDKPackager'
mappings in Universal ++= {
      val configDir = sourceDirectory.value/"main"/"resources"
      for {
        file <- (configDir ** AllPassFilter).get
        relative <- file.relativeTo(configDir.getParentFile)
        mapping = file -> relative.getPath
      } yield mapping
    }
```

Since there is no key in `com.typesafe.sbt.packager.jdkpackager.JDKPackagerKeys` for `fx:resource` I assumed resource mapping should be inherited from Universal plugin. However, created bundles do not contain the specified resources directory. Is there another way to achieve that?

**Comment by muuki88** [comment]
Hi @smoes , thanks for your report.

> I assumed resource mapping should be inherited from Universal plugin

This should indeed [be the case](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/jdkpackager/JDKPackagerPlugin.scala#L55). Can you tell us which native-packager version you are using?

Another thing you could try (and can use for convenience) are the [mappings helper](http://sbt-native-packager.readthedocs.org/en/latest/formats/universal.html#mappingshelper).

```scala
import NativePackagerHelper._
mappings in Universal ++= contentOf(resourceDirectory.value)
```

**Comment by smoes** [comment]
I am using native-packager version `1.1.0-RC1`.
The proposed snippets does not solve the problem. 

To be clear: The defined files/folders are just not present in the resulting bundle itself but appear in `target/jdkpackager`

**Comment by metasim** [comment]
Take this with a grain of salt, as it's been a while since I've looked into it, but the `javapackager` API itself does not provide a clear way of delivering additional files with your `.dmg` or `.pkg` image. It's possible to get things located inside the `.app` bundle, but that's usually not what you want. On Windows `javapackager` has more flexibility, but I can't remember if it requires an override of the WiX/Inno files, or if it just "does the right thing".

One thing that would help get us toward a solution would be a scripted test to build a solution against.
