### ISSUE TITLE
Add a way to specify a docker command / docker binary

### ISSUE THREAD

**Issue by schmitch** [sbt/sbt-native-packager#783]
Actually when deploying to Google Cloud I need to invoke the `gcloud docker` Command so that I could publish images. (it adds some token refresh mechanism but is actually just a wrapper of docker)
However due to the nature of sbt-native-packager I would need to run two steps instead of one to publish / deploy a new image to gcloud.

**Comment by muuki88** [comment]
Thanks for your feature request. I'm not sure how this would look like. Adding a way to customize the docker command itself seems like a big change for "1 instead of 2" steps.

I would recommend [overriding](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L107-L118) the `docker:publish` or `docker:publishLocal` command.

Furthermore is deployment not in the scope of native packager. This boundary may not be as clear with docker as it is with other packaging formats, but supporting vendor specific deployment tools, is.
