### ISSUE TITLE
Scoping for docker-related keys in DockerPlugin

### ISSUE THREAD

**Issue by thetristan** [sbt/sbt-native-packager#796]
I was curious why the `dockerBaseImage`, `dockerExposedPorts`, and `dockerExposedVolumes` keys aren't scoped to the `Docker` configuration like many of the other keys used by the `dockerCommands` key. 

Is this inconsistency intentional? If not, would you be willing to accept a PR that corrects this?

Thanks for the insight.

**Comment by muuki88** [comment]
Intentional. We started introducing a scheme on when and how to name keys and scope them.

- If the setting is plugin specific (e.g. `baseImage` for docker), we prefix it with the plugin name ( leading to `dockerBaseImage` not `baseImage in Docker`). 
- General settings (e.g. `mappings`) get scoped to the according plugin as values differ from scope to scope.

We try to separate plugin-specific settings from general usable settings.

**Comment by muuki88** [comment]
However if you want to fix an issue related to this exact problem, see #789 
Happy to accept pull requests :)

**Comment by thetristan** [comment]
Perfect. Thanks for the fast response. I'll take a look at the issue you referenced. I'd be happy to contribute if possible.
