### ISSUE TITLE
Trouble using *daemonUser* and *daemonGroup* settings for RPM 

### ISSUE THREAD

**Issue by craigwblake** [sbt/sbt-native-packager#856]
I have a build generating an RPM where the daemon user has to be a particular existing user on the target machine.  I've tried using the _daemonUser_ and _daemonGroup_ settings but they are not working as I expect they should be.  I'm setting them with:

``` scala
daemonUser in Rpm := "hadoop"
daemonGroup in Rpm := "hadoop"
```

When I inspect the generated RPM file, the directory in _/var/run_ is created with the _daemonUser_ and _daemonGroup_ ownership, while the _/var/log_ directory is not.

Even so, when installing the RPM the _/var/run_ ownership is apparently ignored, and the resulting daemon does not run as the _daemonUser_ but rather as a new user created to match the project name, like typical.

Any ideas what's going on or what I'm missing?

Thanks.

**Comment by muuki88** [comment]
Thanks for your report. What version fo native-packager are you running? And can you post the complete `build.sbt` that's necessary to reproduce this?

**Comment by zoosky** [comment]
This bug comes with 1.2 refactoring. D  I had  it with rpm and systemv.

**Comment by craigwblake** [comment]
> Which native-packager version are you using
This is with version 1.1.1 of native packager.

> Which system-loader do you use ( SystemV, Upstart oder Systemd)
I did not set one explicitly, but the target system is SystemV style and that's what the package appears to have generated.

> Can you post a minimal build.sbt to reproduce this
I'll see what I can do.

**Comment by MojoJojo** [comment]
I am not sure if this is related but I also noticed that when the rpm is installed, it creates a group and a user matching the project name. I would have thought these two would have matched daemon group and daemon user setting respectively?

**Comment by sheinbergon** [comment]
Still a pesky bug in April 2017. ```daemonUser``` and ```daemonGroup``` are ignored in-favor of user/group name matching the project name. Any word on how to overcome this issue ?

**Comment by keirlawson** [comment]
I found I was able to set them in the Linux scope and it worked for my RPM, ie

```
daemonUser in Linux := "someuser"
```

**Comment by muuki88** [comment]
@keirlawson is correct. You have to scope the `daemonUser` to `in Linux`. This is the reason of a not very well scaling design.

The `linuxScriptReplacements` are being produced by tasks & settings that are scoped to `in Linux`. There are no `linuxScriptReplacements in Rpm`. The current implementation isn't suited for this, because it's

- a `Seq[(String,String)]`, not a `Map` or another easily mergable data structure
- never scoped
- named for linux
- keys are an implementation detail in the `LinuxPlugin`

The whole script generating process needs a big overhaul. I started this 1-2 years a go and did some cleanup, but haven't really touched the architecture itself.
