### ISSUE TITLE
Docker authentication fails with latest milestone

### ISSUE THREAD

**Issue by Daxten** [sbt/sbt-native-packager#892]
Hi,
I have problems with authentication using gitlab-builder / dockerindocker image.

Using version 1.1.4 my buildscripts all work, using the latest milestone I get authentication errors. 
Is this a known issue? If not I would be happy to give you more detailed informations

**Comment by muuki88** [comment]
Hi,

Thanks for your report. This issue seems to be new. I'm a bit puzzled as we have not integrated anything around authentication so nothing that could actually break.

cc @fiadliel

**Comment by fiadliel** [comment]
The default integration never did anything around auth. It assumes that you have already provided credentials so that `docker push` will work.

This was because `docker push` provided no way of giving credentials, other than setting them in the global (ambient) environment, and modifying the global environment seemed like a bad default for a build tool.

So it's an unusual correlation... certainly, please give more information, but I'd be surprised if the root cause had anything to do with this plugin.

**Comment by Daxten** [comment]
y sorry that I didnt react here anymore, closing this is the right choice and I won't be able to reproduce a minimal example for this anymore.

**Comment by muuki88** [comment]
No problem 😉 and thanks for your understanding 😍
