### ISSUE TITLE
Does docker:publishLocal support multiple modules?

### ISSUE THREAD

**Issue by dluc** [sbt/sbt-native-packager#941]
In a project with multiple modules, e.g.
...
/build.sbt
/somelibrary/main/src
/service1/main/src
/service2/main/src
/service3/main/src
...

is it possible to package each service independently, e.g. in this case to 3 different docker images? If so what is the command (from command prompt)?

I'd typically run `sbt docker:publishLocal` but I think the command is different in this case?

Thanks

**Comment by muuki88** [comment]
Sorry for replying this late 😢 . I must have missed this issue.

When you package your projects in sub-modules ( what your example looks like ) then you already get three docker images. E.g. if you have a `build.sbt` like this

```scala
lazy val root = project(".").aggregate(service1, service2, service3)
lazy val service1= project("service1")
    .enablePlugins(JavaAppPackaging)
    .settings(name := "service1")
lazy val service2= project("service2")
    .enablePlugins(JavaAppPackaging)
    .settings(name := "service2")
lazy val service3= project("service3")
    .enablePlugins(JavaAppPackaging)
    .settings(name := "service3")
```

If you call `sbt docker:publishLocal`, all three will  be published as separate docker images.

**Comment by muuki88** [comment]
Sure. Either you configure the native packager plugins only on the sub modules you want or you can all the publish/package command scoped to a submodule `mySubmodule / Docker / publish`

**Comment by dzlab** [comment]
@muuki88 it turns out that `DockerPlugin` was activated for most sub-projects as a result of activating the `JavaAgentPackaging` plugin. This caused those sub-projects to have docker related tasks running.
We can easily confirm this with a sub-project using `.enablePlugins(com.lightbend.sbt.javaagent.JavaAgentPackaging)`.

**Comment by dzlab** [comment]
@muuki88 it turns out that `DockerPlugin` was activated for most sub-projects as a result of activating the `JavaAgentPackaging` plugin. This caused those sub-projects to have docker related tasks running.
We can easily confirm this with a sub-project using `.enablePlugins(com.lightbend.sbt.javaagent.JavaAgent)`.

**Comment by dzlab** [comment]
@muuki88 it turns out that `DockerPlugin` was activated for most sub-projects as a result of activating the `JavaAgentPackaging` plugin (which is brought by `JavaAgent`). This caused those sub-projects to have docker related tasks running. We can easily confirm this with a sub-project using `.enablePlugins(com.lightbend.sbt.javaagent.JavaAgent)`.

How do you suggest calling the publish/package command scoped to a submodule `mySubmodule / Docker / publish`?

**Comment by muuki88** [comment]
What sbt command is triggering the docker related tasks?

Maybe you can try `disablePlugins(...)` on the sub modules you don't want docker tasks running.

**Comment by dzlab** [comment]
I tried `publish` and `stage`, they both seem to have DockerPlugin running. I think I will just override them and use a flag setting to invoke docker tasks if it is set to true.
